name: run Jest Tests
on:
    push:
        branches:
            - main
            - 'develop'
            - 'demo/try_github_actions'
            - 'releases/**'
        paths:
            - '**.js'
            - '**.jsx'
            - '**.ts'
            - '**.tsx'

    pull_request:
        branches:
            - main
            - 'develop'
            - 'demo/try_github_actions'
            - 'releases/**'
        paths:
            - '**.js'
            - '**.jsx'
            - '**.ts'
            - '**.tsx'


jobs:
    run_jest_tests_job:
        name: Run jest test
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-node@v1
                with:
                    node-version: '14.x'
            -   run: yarn --version

            -   name: Get yarn cache directory path
                id: yarn-cache-dir-path
                run: echo "::set-output name=dir::$(yarn cache dir)"

            -   name: Get cache
                uses: actions/cache@v2
                with:
                    path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                    key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-yarn-

            -   name: Install node modules (if not cached)
                if: steps.yarn-cache-dir-path.outputs.cache-hit != 'true'
                run: yarn install --frozen-lock

            -   name: Run jest test
                run: yarn test
